name: deploy-app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - uses: nyaa8/package-version@v1
        with:
          path: "packages/gephi-lite/package.json"

      - name: Build
        run: npm run build
        env:
          BASE_URL: /gephi-lite/v${{ env.PACKAGE_VERSION }}

      - name: Create site folder
        run: mkdir -p website/v${{ env.PACKAGE_VERSION }}

      - name: Copy gephi lite files
        run: cp -rf packages/gephi-lite/build/* website/v${{ env.PACKAGE_VERSION }}

      - name: Create index page with redirection
        run: |
          run: |
          cat <<EOF > website/index.html
          <!DOCTYPE HTML>
          <html lang="en-US">
            <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=/gephi-lite/v${{ env.PACKAGE_VERSION }}">
              <script type="text/javascript">
                window.location.href = "/gephi-lite/v${{ env.PACKAGE_VERSION }}"
              </script>
              <title>Page Redirection</title>
            </head>
            <body>
                If you are not redirected automatically, follow this <a href='/gephi-lite/v${{ env.PACKAGE_VERSION }}'>link to example</a>.
            </body>
          </html>
          EOF

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
