name: deploy-app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - uses: nyaa8/package-version@v1
        with:
          path: "packages/gephi-lite/package.json"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/gephi-lite/build # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
          target-folder: v${{ env.PACKAGE_VERSION }}
